ALTER TABLE Customers
MODIFY CustomerID INT AUTO_INCREMENT;

ALTER TABLE Customers
MODIFY FullName VARCHAR(100) NOT NULL;

ALTER TABLE Customers
MODIFY Email VARCHAR(100) NOT NULL;

ALTER TABLE Customers
ADD CONSTRAINT unique_email UNIQUE (Email);

ALTER TABLE Customers
MODIFY Age INT CHECK (Age >= 0);



